[project]
name = "immich-kiosk-webhook-demo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12.1"
dependencies = [
    "flask>=3.1.2",
    "waitress>=3.0.2",
]
